// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTnSwA6tj4Y7pzToqTpNuZc8NikuNidn0',
    appId: '1:293311041317:web:20c9dc3f3748850ff9d4cc',
    messagingSenderId: '293311041317',
    projectId: 'blackmarket-6981c',
    authDomain: 'blackmarket-6981c.firebaseapp.com',
    storageBucket: 'blackmarket-6981c.firebasestorage.app',
    measurementId: 'G-YMXGKEMEF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB52Gc4PKMIgF5jc5ZmnPYfGSOjflSvv4',
    appId: '1:293311041317:android:ef5769723fad4354f9d4cc',
    messagingSenderId: '293311041317',
    projectId: 'blackmarket-6981c',
    storageBucket: 'blackmarket-6981c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSKT8Fg9oPQRI_rU2OH7mPCUW8Amm0rQc',
    appId: '1:293311041317:ios:3ddaa737ae4dfa99f9d4cc',
    messagingSenderId: '293311041317',
    projectId: 'blackmarket-6981c',
    storageBucket: 'blackmarket-6981c.firebasestorage.app',
    iosClientId: '293311041317-fvamr3th2poh56ouki4rjf5l8a8qk846.apps.googleusercontent.com',
    iosBundleId: 'com.blackMarket',
  );
}
